### ISSUE TITLE
Rails3.1でエラー

### ISSUE THREAD

**Issue by xyslope** [tily/ruby-faker-japanese#1]
private method `rand' called for #Array:0x106498ef8
というエラーが出ます。

下記の修正で動くようです。
-          chosen = instance_variable_get("@#{m}s").rand
-         chosen = instance_variable_get("@#{m}s")[rand(instance_variable_get("@#{m}s").length)]

**Comment by tily** [comment]
レポートありがとうございます。
Rails3.1 ということでしたが手元だと Ruby1.9 で動かなくなっていました。
原因を完全には追えていないのですが、本家 faker gem の Array#rand 実装に依存していたのを、
いただいた修正案を参考に自前で実装してみました。
一応テスト Ruby 1.8.7 と Ruby 1.9.2 の両方で通っています。

https://github.com/tily/ruby-faker-japanese/commit/76a624f45824490756216b3fbfe086f3e742500a

合わせて rubygems.org にアップしている gem ファイルにも反映したので、
よろしければご利用ください。
